
package project_euler;

/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/
public class Question2 
{
    int cap = 4000000;
    //Count up to 4 million
    
    //Get second number, add first number to it, first number becomes second number
    
    int addFib()
    { 
        int b = 2;
        int a = 1;
        int c = 0;
        int evenFib = 0;
        
        while(b < cap)
        {  
            if(b % 2 == 0)
            {
                evenFib += b;
            }     
            c = b;
            b += a;
            a = c;
        }
        return evenFib;
    }
    
    
}
