
package project_euler;

/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/
public class Question2 
{
    

    int cap = 4000000;
    //Count up to 4 million
    
    
    int addFib()
    { 
        int sum = 2;
        int prev = 1;
        int temp = 0;
        int evenFib = 1;
        for(int i = 0; i < cap; i++)
        {  
            temp = prev;
            sum += prev;
            prev = temp;
            
            
            if(temp % 2 == 0)
            {
                evenFib += temp;
            }
            temp =+ sum;
                   
        }
        return sum;
    }
    
    
}
